# Generated by Django 3.0.7 on 2020-06-24 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast_or_roast', models.BooleanField(default=False)),
                ('post', models.CharField(max_length=280)),
                ('up_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('down_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('submission_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
