# Generated by Django 3.0.7 on 2020-06-24 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghostpost',
            name='boast_or_roast',
            field=models.BooleanField(default=False, help_text='Check box to make it a roast!'),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='down_votes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='total_votes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='ghostpost',
            name='up_votes',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
